### ISSUE TITLE
Error: Cannot find module 'fp-ts/boolean'

### ISSUE THREAD

**Issue by Givemeurcookies** [yubinTW/fastify-keycloak-adapter#1]
Importing from node.js (not running Typescript) using the import:
`import keycloak from 'fastify-keycloak-adapter';`

Throws error: 
`Error: Cannot find module 'fp-ts/boolean'`

**Comment by yubinTW** [comment]
thanks for reporting this issue

please update fastify-keycloak-adapter to version >= `0.4.1`
