### ISSUE TITLE
Failed to start test

### ISSUE THREAD

**Issue by clabnet** [yubinTW/fastify-keycloak-adapter#25]
Hello, 
I would try to execute tests on this project. 
Into "server with keycloak testing" suite the KeycloakContainer won't start and this go to stop after timeout. 
I have a keycloak server on my local machine. It run on same port 8080 of your test. 
I have this doubt. My leycloak server must run or not to execute your tests succesfully ?
But I have tried with off/on my local keycloack server, and the result is the same. The container won't start.
Any chance to run tests ?
Thank you.

**Comment by clabnet** [comment]
Sorry, my mistake. 
Your test running fine.

**Comment by yubinTW** [comment]
thx your suggestion
