### ISSUE TITLE
how to use this adapter with Fastify

### ISSUE THREAD

**Issue by clabnet** [yubinTW/fastify-keycloak-adapter#27]
Hello, 
I have a running local instance of keycloak server and one Fastify microservice for REST APIs. 
I need to authenticate these routes with token produced by keycloak.

I created this Fastify plugin :
```
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify'
import fp from 'fastify-plugin'
import { config } from '@/core/config'
import keycloak, { KeycloakOptions } from 'fastify-keycloak-adapter'

export default fp(async (fastify: FastifyInstance) => {
  const unauthorizedHandler = (request: FastifyRequest, reply: FastifyReply) => {
    reply.status(401).send(`Unhauthorized request`)
  }
  const opts: KeycloakOptions = {
    appOrigin: config.keycloakWebOrigins,
    keycloakSubdomain: config.keycloakSubdomain,
    useHttps: true,
    clientId: config.keycloakClientId,
    clientSecret: config.keycloakClientSecret,
    logoutEndpoint: '/logout',
    unauthorizedHandler: unauthorizedHandler
  }
  await fastify.register(keycloak, opts)
  fastify.log.debug('Registered plugin fastify-keycloak-adapter')
})

```
Sorry for dumb question, but what is required to protect my routes ?

Thank's in advance.

**Comment by yubinTW** [comment]
Hi, @clabnet 
`fastify-keycloak-adapter` is a fastify plugin, so you can just setting the options of this plugin and register it (doesn't need to wrapper in `fastify-plugin`)

In default, it will protect all routes,
and use `excludedPatterns` options for setting some urls pattern that you dosen't need to protect

**Comment by yubinTW** [comment]
Hi, @marten-cz 
you can see the [usage session in README](https://github.com/yubinTW/fastify-keycloak-adapter#usage)

this plugin will help your app communicates with keycloak server, and decode `id_token` to `session.user`, and the developer can easily know who send the request.

for example

```typescript
const server = fastify()

// register plugin, ref: https://github.com/yubinTW/fastify-keycloak-adapter#usage
// server.register(...)

// by registering the plugin, this endpoint will be protected
server.get('/some-api-endpoint', (request, reply) => {
  // you can get user from session
  const user = request.session.user
  // your business logic
  // ...
  return reply.status(200).send({ msg: 'something' })
})
```
