### ISSUE TITLE
How to get current token from keycloak

### ISSUE THREAD

**Issue by clabnet** [yubinTW/fastify-keycloak-adapter#39]
I have added this plugin to my fastify server and I can access to API's with token verified by my keycloak issuer.
When I access to user's database with correct email and password, how to get the keycloak token ? 

e.g.
```
 if (correctPassword) {
    return { accessToken: ????? };
  }
```

Thank's

**Comment by yubinTW** [comment]
hi, this plugin use [grant](https://github.com/simov/grant) as the dependency

you can take the token like this

```typescript
const server: FastifyInstance = fastify()
// ...
// after register the `fastify-keycloak-adapter`

server.get('/my-tokens', async (request, reply) => {
    const id_token = request.session.grant.response?.id_token
    console.log('id_token', id_token)
    const access_token = request.session.grant.response?.access_token
    console.log('access_token', access_token)
    const rehresh_token = request.session.grant.response?.refresh_token
    console.log('rehresh_token', rehresh_token)
    return reply.status(200).send({ id_token, access_token, rehresh_token })
  })
```

in this code `request` is `FastifyRequest`,
`request.session.grant.response` is `GrantResponse` ([ref](https://github.com/simov/grant/blob/5f60a595161aa96cd110192bc810eb8fa478da21/grant.d.ts#L318))
