### ISSUE TITLE
'fastify-keycloak-adapter' does not provide an export named 'default'

### ISSUE THREAD

**Issue by mstimvol** [yubinTW/fastify-keycloak-adapter#42]
When I import this adapter:

> import keycloak from 'fastify-keycloak-adapter'

It says:

> SyntaxError: The requested module 'fastify-keycloak-adapter' does not provide an export named 'default'

I'm using 2.1.7 of the adapter. Any idea how to fix this issue?

**Comment by yubinTW** [comment]
hi, try `2.1.8` version.
if it's not work as well, could you give me some code to reproduce your situation?

**Comment by mstimvol** [comment]
Hi @yubinTW Using 2.1.8 works perfectly. Thanks for fixing the issue!
