### ISSUE TITLE
Add support for optional authorization

### ISSUE THREAD

**Issue by dwelch2344** [yubinTW/fastify-keycloak-adapter#51]
Great work on this adapter! I'm just playing around with it now and it works great out of the box, but I find myself wanting to conditionally identify a principal _if_ there's an authorization header, otherwise still allow the request to run. 

It's been a while since I've worked with `fp-ts` so figured I'd ask if this is something you'd be willing to support, if contributed. Thoughts?

**Comment by yubinTW** [comment]
Sure, feel free to send the PR

**Comment by ArnaudTA** [comment]
@dwelch2344 look at #52 my problem was pretty similar and I hope you'll be able to use this option
