### ISSUE TITLE
/logout No Longer Supports "redirect_uri" as default from v18.0.0

### ISSUE THREAD

**Issue by EnriqueJMP-holcim** [yubinTW/fastify-keycloak-adapter#54]
Hi @yubinTW,

Amazing work on this plugin! I wanted to report an issue we're experiencing with Keycloak 18.0.0, specifically regarding the `/logout` endpoint functionality. According to the [official documentation](https://github.com/keycloak/keycloak/blob/da5fd31a5f7c92af4a9843a4b46938972e39ff24/docs/documentation/upgrading/topics/changes/changes-18_0_0.adoc#openid-connect-logout), a breaking change has been introduced starting from version 18.0.0. Future versions will likely remove the ability to specify the `redirect_uri` in the logout request.

[Link](https://github.com/keycloak/keycloak/blob/da5fd31a5f7c92af4a9843a4b46938972e39ff24/docs/documentation/upgrading/topics/changes/changes-18_0_0.adoc?plain=1#L33)
>   Consider either removing the `redirect_uri` parameter entirely or replacing it with the `id_token_hint` and `post_logout_redirect_uri` parameters.
The backwards compatibility switch will be removed in some future version - probably Keycloak 23. You are encouraged to update your clients as soon as possible as described above rather than rely on this switch.

Currently, an error message is thrown when doing a logout:

> Invalid parameter: redirect_uri

### Investigation

I reviewed the source code of the official (and now deprecated) `keycloak-nodejs-connect` library. They handle this by adding the `post_logout_redirect_uri` and `id_token_hint` parameters. The `id_token_hint` parameter is automatically populated with the `id_token` from the grant response.

Here, they automatically populate the `id_token_hint` parameter from `grant.id_token`:
[Link](https://github.com/keycloak/keycloak-nodejs-connect/blob/cee3608b35273d9e37f70fa9b5f24d8465bb9870/middleware/logout.js#L29C7-L29C55)
```javascript
    let idTokenHint = null
    if (request.kauth.grant) {
      idTokenHint = request.kauth.grant.id_token.token
      ....
    }
``` 

[Link](https://github.com/keycloak/keycloak-nodejs-connect/blob/cee3608b35273d9e37f70fa9b5f24d8465bb9870/keycloak.js#L406)
```javascript
Keycloak.prototype.logoutUrl = function (redirectUrl, idTokenHint) {
  const url = new URL(this.config.realmUrl + '/protocol/openid-connect/logout')

  if (redirectUrl && idTokenHint) {
    url.searchParams.set('id_token_hint', idTokenHint)
    url.searchParams.set('post_logout_redirect_uri', redirectUrl)
  }

  return url.toString()
}
``` 

### Solution Proposal

A non-breaking solution that works both ways could be beneficial. This solution would handle both the `redirect_uri` parameter and the new way of specifying the logout redirect URL.

I propose adding a new partial `keycloakOption`, such as a boolean flag, to instruct the library to build the logout URL using the new parameters. If this flag is not set, the library should default to using the current `redirect_uri`.

[Link](https://github.com/yubinTW/fastify-keycloak-adapter/blob/e9cc9d370b6a0bae069a3fa981cbf333ca78090d/src/keycloak.ts#L80)
```javascript
const partialOptions = t.partial({
  ...
  XXXXXX: t.readonly(t.boolean),
  ...
})
```

Around this code line, you could implement the logic to build the logout URL using either the old `redirect_uri` or the new parameters, depending on the optional flag mentioned above.
[Link](https://github.com/yubinTW/fastify-keycloak-adapter/blob/e9cc9d370b6a0bae069a3fa981cbf333ca78090d/src/keycloak.ts#L503)
```javascript
              E.map((config) => reply.redirect(`${config.end_session_endpoint}?redirect_uri=${opts.appOrigin}`))
``` 

Additionally, you could use the `id_token` from the grant response to automatically populate the `id_token_hint` parameter.
[Link](https://github.com/simov/grant/blob/5f60a595161aa96cd110192bc810eb8fa478da21/grant.d.ts#L330)
```javascript
/**
 * Grant response
 */
export interface GrantResponse {
  ....
  /**
   * OpenID Connect id token
   */
  id_token?: string
  ....
```

### Final Thoughts

I conducted some manual tests by directly calling my Keycloak `/logout` URL endpoint with the new parameters in the browser. It appears to work correctly, redirecting me as expected and not throwing any invalid parameter errors.

Thank you for your attention!

**Comment by yubinTW** [comment]
Hi @EnriqueJMP-holcim,

Thank you so much for your detailed issue! Your investigation and proposed solution were extremely helpful. I've modified the code (#56), and a new version of the library has been published. 

Try the `2.3.0` version, and set `usePostLogoutRedirect` to `true` when using keycloak version >= 18
