### ISSUE TITLE
Update deprecated `routeConfig` usage

### ISSUE THREAD

**Issue by pinussilvestrus** [yubinTW/fastify-keycloak-adapter#58]
Hi!

We receive a couple of deprecation warnings due to the use of `request.routeConfig`. As we do not use the method on our own, and checked other fastify libraries, we came to the conclusion that it's due to a use in this library:

https://github.com/yubinTW/fastify-keycloak-adapter/blob/d499594de4795bbb223640d2d8979a8834f298b9/src/keycloak.ts#L323

> (node:1) [FSTDEP016] FastifyDeprecation: You are accessing the deprecated "request.routeConfig" property. Use "request.routeOptions.config" instead. Property "req.routeConfig" will be removed in `fastify@5`.

Is there any chance to get an update here? Thanks in advance 🙂

**Comment by yubinTW** [comment]
hi, thanks
Please try version `2.3.2`
